### PR TITLE
[HOLD][SHARE-603][Feature] Add sorting by source

### PR DESCRIPTION
**Pull request by leb2dg**
## Purpose

Add more sorting options.

## Changes

Add sort by sources

screen shot 2017-02-22 at 10 24 54 am

## Side effects

None

## Ticket

https://openscience.atlassian.net/browse/SHARE-603

### CODE REVIEW

**Comment by chrisseto** [comment]
Does this not have the same issues as sorting on title?

What's the behavior when something has multiple sources?

**Comment by leb2dg** [comment]
Ah, did not think about multiple sources...

It's definitely weird: https://share.osf.io/discover?sort=sources&sources=arXiv%2CCrossRef

**Comment by aaxelb** [comment]
I feel like sorting by source might be even less useful than sorting by title...

**Comment by leb2dg** [comment]
Closing for now as discussed on [SHARE-603](https://openscience.atlassian.net/browse/SHARE-603). Will reopen if use case aligns with priorities.

**Pull request closed without merging**
