### PR TITLE
[SHARE-468] [Feature] Add COS footer

### PR DESCRIPTION
**Pull request by leb2dg**
### Purpose
Add the copyright to all pages.

### Changes
* Copyright on all pages
* New footer that has links
    * something else can go there but it looks weird without a footer
* Cleaned up style in templates
* Removed "Developer docs" link from index page and added new version to footer

### Ticket
https://openscience.atlassian.net/browse/SHARE-468

screen shot 2016-12-20 at 2 57 55 pm
screen shot 2016-12-20 at 2 58 10 pm

### CODE REVIEW

**Comment by aaxelb** [comment]
Is it just me, or are the three lists in the footer unevenly spaced? Is each list centered in the column, so their spacing depends on the length of the links?

**Comment by leb2dg** [comment]
Centering things is hard...

**Comment by aaxelb** [comment]
Is there something wrong with plain ol' left justification?

**Comment by leb2dg** [comment]
Not really, it just looks pretty weird. The styling can be worked on if we want to keep it though, no point otherwise ¯\\_(ツ)_/¯

**Comment by aaxelb** [comment]
I like the footer, I think we should keep it! Maybe just a little more polish, though ✨

**Comment by chrisseto** [comment]
Quick ping to either @saradbowman or @rickjohnson to make sure that the copyright is okay.

**Comment by chrisseto** [comment]
Missed the first bit of the ticket, this is already on the share site.

Can you go ahead and bump 2016 to 2017?

Otherwise LGTM :egg:

**Pull request merged**
